### ISSUE TITLE
Broken/outdated links in the documentation

### ISSUE THREAD

**Issue by vaguirrebkoch** [BASTAcode/BASTA#15]
The "source code structure" section is not correctly linking to the functions and comments (e.g., the BASTA main functions)

**Comment by jakobmoss** [comment]
Hmm.. It seems to be a problem with the Sphinx build on ReadTheDocs. It works when I build it locally as shown in the screenshot below. I will investigate!

![Screenshot 2022-08-16 at 09 42 21](https://user-images.githubusercontent.com/9656902/184825287-bcc48651-ac66-4cd3-88e1-def85b890002.png)

**Comment by jakobmoss** [comment]
It it fixed on the devel-branch now. It was a configuration issue in `conf.py` causing the issues on ReadTheDocs. See: https://basta.readthedocs.io/en/devel/source_mainfuncs.html .

I will close the issue when it is merge into main.

**Comment by jakobmoss** [comment]
Fixed in version 1.1.6
