### ISSUE TITLE
Add the starid to the plots

### ISSUE THREAD

**Issue by amaliestokholm** [BASTAcode/BASTA#45]
When studying multiple pdfs at a time, I usually combine them into a single pdf using pdfjam and look at them by scrolling through for faster assessment.

However, the downside of this method is that the starid is no longer available as this is only saved in the name of the figure as part of `outputname`.

It would be great to either have a flag or a default where the name of the star is added to the Kiel and corner plots.

This could be done in `plot_driver.py` by splitting `outputname` on `/` and take index `-1` and then adding it to the figure using annotate or the like. It can be in tiny font.

**Comment by MLWinther** [comment]
I have (very plainly) added the feature to include it in corner plots and Kiel diagrams, and set up a pull request.
Examples are as below, is this the desired behavior?
![16CygA_corner](https://github.com/BASTAcode/BASTA/assets/36820590/f48831be-786e-4fe8-9f86-d8fc9b2b4c42)
![16CygA_kiel](https://github.com/BASTAcode/BASTA/assets/36820590/8864d388-c69e-4ef2-9cd2-6769c6d72a30)

**Comment by amaliestokholm** [comment]
This is exactly that - thank you!
