### ISSUE TITLE
Add BASTA to PyPI

### ISSUE THREAD

**Issue by jakobmoss** [BASTAcode/BASTA#55]
Make BASTA available for download using standard `pip install basta`. Following the suggestion in #54 .

Remember to consider how we ship examples and the template input files.

Two step process:
1) Add the current version of the code with a simple note in the documentation [now].
2) Improve on auxiliary tools to make it easier to run things just from the command line (e.g., to create input files by answering questions etc.). [later]

@jakobmoss will look into it.

**Comment by mr-asher** [comment]
Let me know if I can help with this.

**Comment by jakobmoss** [comment]
Included in the release [v1.5.0](https://github.com/BASTAcode/BASTA/releases/tag/v1.5.0) .
